### ISSUE TITLE
Feature parity in terms of packages with dynamic

### ISSUE THREAD

**Issue by mmanciop** [instana/instana-agent-docker#21]
In the dynamic and static images we integrate more packages, like `python-pip`, `inotify-tools`, `docker-ce-cli` and `containerd`, but the `rhel` build does not seem to carry it:

https://github.com/instana/instana-agent-docker/blob/09642c6dd835aaf3a73005a553194dbdf7338647/rhel/Dockerfile#L39

**Comment by mdonkers** [comment]
Got resolved a while ago by moving everything to RHEL based images.
